#!/bin/bash

USER_DEFAULT_DIRECTORIES="$HOME/Desktop"
USER_DEFAULT_OUTPUT_DIRECTORIES="$HOME/Desktop"
GREPFUL_SOURCE_DIRECTORY="$XIIIOUSZ_HOME/grepful/file/source"
GREPFUL_OUTPUT_DIRECTORY="$XIIIOUSZ_HOME/grepful/file/output"
